// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG6kWuqv1nZYdLS02SO1sirPnNwhwNM3o',
    appId: '1:217856905940:web:6e0177c87de602d9432141',
    messagingSenderId: '217856905940',
    projectId: 'my-cool-projecct123',
    authDomain: 'my-cool-projecct123.firebaseapp.com',
    storageBucket: 'my-cool-projecct123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIAMvWzakiQ6P9GAqPAmMoYKX7FMvAIWI',
    appId: '1:217856905940:android:c936a1dd10654495432141',
    messagingSenderId: '217856905940',
    projectId: 'my-cool-projecct123',
    storageBucket: 'my-cool-projecct123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlcQgxlufvTRRWMm8r1Iup9cYQo0zG_QA',
    appId: '1:217856905940:ios:69d132fb6c08239b432141',
    messagingSenderId: '217856905940',
    projectId: 'my-cool-projecct123',
    storageBucket: 'my-cool-projecct123.firebasestorage.app',
    androidClientId: '217856905940-bf7p0167flcrt9jj2re4fe1k4qj4t9e5.apps.googleusercontent.com',
    iosClientId: '217856905940-qicr7igmih5un8j6ek40pptsg8c657f0.apps.googleusercontent.com',
    iosBundleId: 'com.example.totalxproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlcQgxlufvTRRWMm8r1Iup9cYQo0zG_QA',
    appId: '1:217856905940:ios:69d132fb6c08239b432141',
    messagingSenderId: '217856905940',
    projectId: 'my-cool-projecct123',
    storageBucket: 'my-cool-projecct123.firebasestorage.app',
    androidClientId: '217856905940-bf7p0167flcrt9jj2re4fe1k4qj4t9e5.apps.googleusercontent.com',
    iosClientId: '217856905940-qicr7igmih5un8j6ek40pptsg8c657f0.apps.googleusercontent.com',
    iosBundleId: 'com.example.totalxproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5lGXqabP-vldIByzLQ8ofsWNVs31IPto',
    appId: '1:217856905940:web:05cd423900da05ce432141',
    messagingSenderId: '217856905940',
    projectId: 'my-cool-projecct123',
    authDomain: 'my-cool-projecct123.firebaseapp.com',
    storageBucket: 'my-cool-projecct123.firebasestorage.app',
  );
}
